# Package set up
renv::record(
  c(
    "renv",
    "dfe-analytical-services/dfeshiny",
    "dfe-analytical-services/dfeR",
    "dfe-analytical-services/eesyapi",
    "dfe-analytical-services/eesyscreener",
    "dfe-analytical-services/shinyGovstyle",
    "ggplot2",
    "ggiraph",
    "sf",
    "shiny",
    "shinytest2",
    "systemfonts",
    "terra"
  )
)
renv::restore()
